name: 'Set up Emacs'
description: 'Install a specific Emacs version for use in your workflow.'
author: 'Steve Purcell'
inputs:
  version:
    description: 'The version of Emacs to install, e.g. "24.3", or "snapshot" for a recent development version.'
  repository:
    description: 'The GitHub repository containing nix-emacs-ci builds'
    default: 'purcell/nix-emacs-ci'
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/install.sh
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        GITHUB_TOKEN: ${{ github.token }}
